services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
<<<<<<< HEAD
    container_name: backend_container
=======
    container_name: backend-container
>>>>>>> 090afaa3c9689a87a10a92dab32bc1df71a88c63
    ports:
      - "3000:3000"
