services:
  nginx:
    image: agrelloa1/nginx:7bd1ba0
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
  frontend:
    image: agrelloa1/frontend:7bd1ba0
    container_name: frontend-container
  backend-1:
    image: agrelloa1/backend:7bd1ba0
    container_name: backend-container-1
  backend-2:
    image: agrelloa1/backend:7bd1ba0
    container_name: backend-container-2
